name: twinhunter
base: core18 # the base snap is the execution environment for this snap
version: "0.1.3"
summary: A Simple duplicate file finder
description: |
  A Simple duplicate file finder.

grade: stable
confinement: strict

apps:
  twinhunter:
    command: twinhunter

parts:
  twinhunter:
    plugin: go
    source: .
    go-importpath: twinhunter

plugs:
  twinhunter-home:
    interface: home
  twinhunter-removable-media:
    interface: removable-media
