name: twinhunter
base: core24
version: "1.1.0"
summary: A Simple duplicate file finder
description: |
  A CLI tool to find and clean duplicate files.

grade: stable
confinement: strict

apps:
  twinhunter:
    # The go plugin places binaries in bin/
    # This must match the module name in your go.mod
    command: bin/twinhunter
    plugs:
      - home
      - removable-media

parts:
  twinhunter:
    plugin: go
    source: .
    # This automatically runs go install ./...
    # and places the results in the correct internal directories
    build-snaps:
      - go/latest/stable
